### ISSUE TITLE
Discussion: Many providers in application.

### ISSUE THREAD

**Issue by rbgfloripa** [dai-shi/react-tracked#19] opened 2019-09-16 19:23 UTC
Hi !!  :-)   Rafael here again.  lol

I have a provider as below:

```
import React, { useReducer } from "react";
import { createContainer } from "react-tracked";

const reducer = (state, newObject) => { return { ...state, ...newObject } };

export const { Provider, useTracked: useContainerState } = createContainer(
    () => useReducer(reducer, {})
);

export const ContainerProvider = ({ children }) => <Provider> {children} </Provider> ;
```

And I'm using that provider wrapping any route of my application. To create a context to any component route.

```
const PrivateRoute = ({ component: Component, ...rest }) => {
    return (
        <Route
            {...rest}
            render={props => validLogin()
                ? <ContainerProvider> <Component {...props} {...rest} /> </ContainerProvider>
                : <Redirect to="/login"/>
            }
        />
    );
};

const WorkflowRoutes = () => (
    <Switch>
        <PrivateRoute exact path="/dashboard" component={Dashboard} />
        <PrivateRoute exact path="/audit" component={Audit} />
    ....
```

The problem is...  
If I access the dashboard module and then access the audit module, the object contained in the state (useTracked) in audit module will have all the objects that were in the dashboard. It is sharing the data instead of having one provider for each module.

Is there any way to create a unique provider for each module?
I imagine this is happening because the reducer is not being created in ContainerProvider. 
Is there any way around this?

Thanks a lot again !

Rafael.

**Comment by dai-shi** [comment] 2019-09-16 22:40
Interesting use case.
I would like dig into it.
Would you help me by creating a smaller reproduction without Router?

**Comment by rbgfloripa** [comment] 2019-09-17 01:06
yes of course.
I'll create a sandbox and sent it to you as soon as it's ready.
Thanks.

**Comment by rbgfloripa** [comment] 2019-09-17 01:30
Here we go !!   

https://codesandbox.io/s/quizzical-sammet-qt3jt

**Comment by rbgfloripa** [comment] 2019-09-17 02:11
There are some errors in the route that I could not find out...  :(
But tomorrow morning (it's 23hs now in Brazil) I'll fix it.
This is the main idea.

Thanks.

**Comment by dai-shi** [comment] 2019-09-17 02:14
Have a good night!
One big question of mine is whether this issue is Router-related, or in general.
So, I wish you can create a reproduction without Router.
I will take a look at it later anyway.

**Comment by rbgfloripa** [comment] 2019-09-17 02:24
https://codesandbox.io/s/dreamy-tu-37etm
Apparently without the router, it works.

**Comment by dai-shi** [comment] 2019-09-17 02:27
> Apparently without the router, it works.

That's good to know.

**Comment by jminnihan** [comment] 2019-11-04 12:42
I too am having issues using react-tracked with the react-router. I am getting the error "Please use <Provider>" while attempting to use the async recipe you have generously provided. Going to track where this error is being thrown from within the code, as my project is now blocked. If you can provide some guidance, that would be fantastic. Thanks for developing this module!

**Comment by jminnihan** [comment] 2019-11-04 12:47
Stack trace:
[Error] Error: Please use <Provider>
	state (bundle.js:177016)
	(anonymous function) (bundle.js:177146:89)
	App (bundle.js:192280:93)
	App (bundle.js:169633)
	renderWithHooks (bundle.js:156192)
	mountIndeterminateComponent (bundle.js:158726)
	callCallback (bundle.js:140287)
	dispatchEvent
	invokeGuardedCallbackDev (bundle.js:140336)
	invokeGuardedCallback (bundle.js:140391)
	beginWork$$1 (bundle.js:165689)
	performUnitOfWork (bundle.js:164616)
	workLoopSync (bundle.js:164589)
	performSyncWorkOnRoot (bundle.js:164188)
	scheduleUpdateOnFiber (bundle.js:163616)
	updateContainer (bundle.js:167012)
	(anonymous function) (bundle.js:167436)
	unbatchedUpdates (bundle.js:164351)
	legacyRenderSubtreeIntoContainer (bundle.js:167435)
	render (bundle.js:195976)
	(anonymous function) (bundle.js:195979)
	./src/index.tsx (bundle.js:196007)
	__webpack_require__ (bundle.js:727)
	fn (bundle.js:101)
	(anonymous function) (bundle.js:199339)
	__webpack_require__ (bundle.js:727)
	(anonymous function) (bundle.js:794)
	Global Code (bundle.js:795)

**Comment by dai-shi** [comment] 2019-11-04 13:08
@jminnihan Hi! Would you possibly provide a smaller codesandbox to reproduce the error?
Last time I tried, I didn't understand the issue. But, I'm pretty sure there are some issues. Your help is appreciated.

**Comment by jminnihan** [comment] 2019-11-04 13:27
Nevermind. I found out after some discovery within your code I wasn't doing it correctly...

In a nutshell:

I attempted to useTrackedState within my App component that also used the <Provider> tag. Since the Provider really wasn't defined yet, your code threw correctly the error.

i.e. 
```
const App: React.FC = () => {
  const dispatch = useDispatch();
  const globalState = useTrackedState();

  return (
    <Provider>
      ...
    </Provider>
  )
}

```
doesn't work **as designed** :-) 
but... the combo of:

```
const App: React.FC = () => {
  return (
    <Provider>
       <Main />
    </Provider>
  )
}

const Main: React.FC = () => {
  const dispatch = useDispatch();
  const globalState = useTrackedState();

  return (
    <div>
      ...
    </div>
  )
}

```
**works beautifully!**

Working out some other issues now... Thanks again for the great library!

**Comment by dai-shi** [comment] 2019-11-04 13:33
@jminnihan Good to hear you figure it out. Yeah, that's a pitfall some may fall in. Please let me know if you have a better idea to improve the error message. Also, feel free to open a new issue if you find any.

**Comment by peterDijk** [comment] 2020-08-12 08:04
Hi,

Thanks for creating this library, it is really helping me in improving my app's performance!
I do have a similar issue:

- I have wrapped the `Provider` around my `App` component.
- In the App I've got a `react-router switch`. 
- In one route, it works fine (`useTrackedState` is used in various components deep down in the tree). Apart from 1 particular component, when useTrackedState is used there I get the `Please use Provider` error. I solved this for now by passing the state through props (the parent of this component can call `useTrackedState` without issues.
- In another route, where `useTrackedState` is called in various components down in the tree I get the same `Please use Provider` error. 

I can't find a consistent difference between the use cases. It seems random??

**Comment by dai-shi** [comment] 2020-08-12 08:16
Hey, thanks for reporting. Random sounds weird.

I'm afraid that I don't yet get what's happening clearly from the beginning of this issue. Would you help us by creating a codesandbox reproduction?

**Comment by peterDijk** [comment] 2020-08-13 13:04
> Hey, thanks for reporting. Random sounds weird.
> 
> I'm afraid that I don't yet get what's happening clearly from the beginning of this issue. Would you help us by creating a codesandbox reproduction?

very sorry, made a stupid mistake by importing the wrong hook ....

**Comment by dai-shi** [comment] 2020-08-13 13:11
No problem! Keep trying and find possible bugs!

Let me close this issue. If anybody finds a similar issue, please open a new issue.

**Closed by dai-shi** 2020-08-13 13:11 UTC
Labels: needs repro
