### ISSUE TITLE
Global State Does Not Seem To Persist Between Page Routes When using React Router.

### ISSUE THREAD

**Issue by jminnihan** [dai-shi/react-tracked#27] opened 2019-11-11 20:34 UTC
I can't seem to hold on to a global state value using useTrackedState(), it seems like when a React Router `<Route>` component is used, the state is re-initialized. This could just be an issue with my application architecture, but I'd like some feedback none the less...

Here's an example test application from my personal GitHub repository: [GitHub:react-tracked-test](https://github.com/jminnihan/react-tracked-test).

Thanks for any help you can provide.

**Comment by dai-shi** [comment] 2019-11-12 06:05
Wow, it's so nice to see you try react-tracked and use-reducer-async.

There seems nothing obviously wrong. So, you need to dig in more.
I think React Router keeps Context, so in general React Tracked should work. But, there can be a bug because I didn't use react-router extensively and might miss something.

Would you try to create a smaller reproduction code? That should help find an issue anyway.

**Comment by wibed** [comment] 2020-10-08 12:41
I have the same issue:

i define the shared state like this 
```ts
import { useState } from "react";
import { createContainer } from "react-tracked";

const globalState = {
    authenticated: false,
};

const useMyState = () => useState(globalState)

export const {
    Provider: SharedStateProvider,
    useTracked: useSharedState,
} = createContainer(useMyState)

```

and access it like this:
```
import { useSharedState } from '../../App/Store';

const Something = (props) => {
  const [global, setGlobal] = useSharedState();
```

the problem is, when i log at each rerender (this is a recreation of the login process)
```
Route("/"), ==> authenticated === false
Route("login"), ==> authenticated === false
Route("user"), ==> authenticated === true
Route("/"), ==> authenticated === false
```
why isnt it persistend, once it changed???

**Comment by dai-shi** [comment] 2020-10-08 22:14
@wibed Hey, thanks for chiming in.
I wonder where you place `SharedStateProvider`. Would it be possible for you to create a minimal repro with codesandbox?

**Comment by wibed** [comment] 2020-10-11 14:49
@dai-shi nope it was me, I am using a framework which expects certain environment to get a global state to work
so after testing in code sandbox I couldn't find any non persistent state. 

kudos to you

**Comment by dai-shi** [comment] 2020-10-11 22:10
> how could I extract the props from SharedStateProvider?

Do you want to receive props in Provider or pass props to Provider?

> the ideal case would be to use Object.assign() and copy the properties over

Or, do you mean something like this?

```jsx
const MyComponent = (props) => (
  <SharedStateProvider {...props}>
    {React.createElement(FrameworkConst, props)}
  </SharedStateProvider>
);
```

**Comment by wibed** [comment] 2020-10-12 03:29
I doesn't seem to work as expected.

maybe you have a look at:
https://github.com/ionic-team/ionic-react-conference-app/blob/master/src/App.tsx
```
creates a app const, wraps it into a useContext provider while mapping state and dispatch props to props
```

https://github.com/ionic-team/ionic-react-conference-app/blob/master/src/data/AppContext.tsx
```
createContainer and useReducer wrapper, pulling the initialState
```

https://github.com/ionic-team/ionic-react-conference-app/blob/master/src/data/connect.tsx
```
populating props mapping dispatch and state props, returning a react.createElement
```

I'm no react/ts/js developer so I am having a hard time figuring this out by myself. additionally Id rather like to interface with a dependency, which is probably updated by people more knowledgable than myself, as to keep my own code, and
mess up sooner or later.

**Comment by dai-shi** [comment] 2020-10-12 09:39
Thanks for your investigation. Seems like a bug or an expected behavior.
I need a tiny repro, something smaller than 07_todolist.
Maybe just one count, and two pages. Will try.

**Comment by wibed** [comment] 2020-10-12 11:48
@dai-shi I ended up using zustand:
https://github.com/pmndrs/zustand

**Comment by dai-shi** [comment] 2020-10-12 12:09
https://codesandbox.io/s/dreamy-ishizaka-gq3y6?file=/src/index.js
I added react-router v5 to the minimal example, and it seems working.
Would somebody create an example to reveal the issue?

**Comment by wibed** [comment] 2020-10-12 13:06
above an example app and the Context API used to create its provider is linked, where replacing the AppContextProvider with the useTracked.Provider state does not persist

**Comment by dai-shi** [comment] 2020-10-12 13:22
So, unless it's "linked", state persists? Does "linked" have anything to do with react-router? I'm not sure if I understand the problem.

**Comment by wibed** [comment] 2020-10-12 14:08
no, state does not persist. in any case. 

I try to use useTracked as a provider. the example app, uses the new `useContext` api. 
I hoped you could tell me how I have to initiate the provider so I can use it, just like the existing store in the example app.
https://github.com/ionic-team/ionic-react-conference-app/blob/master/src/App.tsx

**Comment by wibed** [comment] 2020-10-13 07:14
ill test it right away

**Comment by wibed** [comment] 2020-10-14 09:12
> I tried again. and this time I put the router element on the correct place.
it seems my links have defaulted to a full page reload instead of navigating in-between components which caused the state to reset. @dai-shi thank you very much for providing so much help

I tested it once more using the `useState` pattern as seen in example 07.
<3 works as expected.

**Comment by dai-shi** [comment] 2020-10-14 10:33
@wibed Nice to hear you solved your issue! Please let me know if you have any other questions.

Let me close this issue as it gets long for broader topics. If someone finds an issue about react-router or something else, please file a new issue. Thanks.

**Closed by dai-shi** 2020-10-14 10:33 UTC
Labels: help wanted, needs repro
