### ISSUE TITLE
Typescript is not happy with react-tracked.  What am I missing here?

### ISSUE THREAD

**Issue by clechner77** [dai-shi/react-tracked#59] opened 2020-08-01 07:29 UTC
Ideas how to work around this with Provider?

(alias) const Provider: React.ComponentType<unknown>
import Provider
JSX element type 'ReactElement<any, any> | Component<unknown, any, any>' is not a constructor function for JSX elements.
  Type 'Component<unknown, any, any>' is not assignable to type 'Element | ElementClass'.
    Type 'Component<unknown, any, any>' is not assignable to type 'ElementClass'.
      The types returned by 'render()' are incompatible between these types.
        Type 'ReactNode' is not assignable to type 'false | Element'.
          Type 'string' is not assignable to type 'false | Element'.ts

**Comment by dai-shi** [comment] 2020-08-01 07:38
Hi, I'm not sure if I understand how this is happening. Would it possible to create a reproduction, possibly with codesandbox.

One thing in mind is`React.ComponentType` is not like what I expected. Would you be able to change it to `React.FC` and see if it works?

**Comment by Aslemammad** [comment] 2020-08-08 07:14
I'm so happy with this Project. If you want, I can move it to typescript and have better types. because most of my projects are ts. Is it OK to take the PR and change all the files to real ts?

**Comment by dai-shi** [comment] 2020-08-08 08:29
@Aslemammad Hey, thanks for volunteering!

Actually, I already developed v2 in all TS. https://github.com/dai-shi/react-tracked/pull/43
We are waiting for React to finalize their new hook.

In that sense, we shouldn't spend too much effort for v1. I think we can just modify the current index.d.ts in v1 to fix the issue reported here. Do you know what the issue is?

I wonder if @clechner77 is still around.

**Comment by Aslemammad** [comment] 2020-08-08 10:10
OOOh thanks, Maybe I'll take the other issues.

**Comment by dai-shi** [comment] 2020-09-08 02:45
eb0c9d76f43621e7957ccded5f044a8cba5e4c6d changed it to `FC`. Hoping it helps...

**Comment by clechner77** [comment] 2020-09-08 03:44
Sorry, I am alive!!!!  Long story....

Simple change to FC may be all that's needed.

**Comment by dai-shi** [comment] 2020-09-08 06:58
Published: https://www.npmjs.com/package/react-tracked/v/1.4.2

I'm not quite sure if this resolves the issue described here, but let me close this. Feel free to reopen this if the problem persists.

**Closed by dai-shi** 2020-09-08 06:58 UTC
