### ISSUE TITLE
Unexpected behavior when map() is applied to the property of the tracked state

### ISSUE THREAD

**Issue by ShamansCoding** [dai-shi/react-tracked#66] opened 2020-10-08 11:15 UTC
Greetings! I have an action in my reducer which map over an array in the store:

```javascript
setMyArrayInStore: ({ payload, store }) => {
    const { rowData, type } = payload;

    return {
      myArrayInStore: store.myArrayInStore.map(
        (item) => {
          if (item.field !== rowData.field) {
            return item;
          }

          return {
            ...item,
            [type]: rowData[type],
          };
        }
      ),
    };
  },
```

In another part of my code, I'm using myArrayInStore as a useEffect() dependency. 

```javascript

const { myArrayInStore } = useTrackedState();

useEffect(() => {
  ...some actions on myArrayInStore change
}, [myArrayInStore], 
```

Without react-tracked useEffect() recognize that myArrayInStore was recreated and fires actions inside.

When I change the code to use react-tracked, useEffect() no longer fire actions.

**Comment by dai-shi** [comment] 2020-10-08 11:22
Hi, thanks for reporting.
It sounds weird but I don't see anything obviously wrong in your snippet.
Would it be possible for you to create a minimal codesandbox that reproduce the issue?

**Comment by ShamansCoding** [comment] 2020-10-08 12:39
> Hi, thanks for reporting.
> It sounds weird but I don't see anything obviously wrong in your snippet.
> Would it be possible for you to create a minimal codesandbox that reproduce the issue?

Yes, here two examples below:

[Working store](https://codesandbox.io/s/working-store-4m18w)
[Not working store](https://codesandbox.io/s/not-working-store-cmkby)

**Comment by dai-shi** [comment] 2020-10-09 00:11
Thanks for the example! I understand what's happening.

This happens because you change the state object reference, but the internal values are not changed. When `useTrackedState` compares two objects (prev state and next state), it doesn't find any differences (= what you display is the same), so it will not re-render (not commit). You might have tried `console.log(myArrayInStore)` and see something, but this only mean it invokes the function (which must be pure), but it's actually not committed (I know this behavior is not desired, but can't be helped for now. v2 with useMutableSource will probably fix this.)

Here's the example that changes what it shows.
https://codesandbox.io/s/not-working-store-forked-inedh?file=/src/MyComponent.js

Another workaround is to use `useSelector` instead of `useTrackedState` if you want to detect the reference change, and all the values are not changed.
```js
const myArrayInStore = useSelector(useCallback(state => state.myArrayInStore, []));
```

Hope it helps!

**Comment by ShamansCoding** [comment] 2020-10-09 08:22
Thanks for reply! I think my example was not too clear, as i see now. So i change it a bit to actually create a new array with new values inside. Actually it was my real case.

[Not working store](https://codesandbox.io/s/not-working-store-cmkby)

The object inside array now really changing, not only the reference. But useEffect() does not recognize it.

**Comment by dai-shi** [comment] 2020-10-09 08:39
> If we change item.name to item.field than noting will happen. Changes not detected by useEffect().

Yes, that's the point. 

```js
  useEffect(() => {
    console.log('render committed');
  });
```

Add this in your component. If you don't see the log, it means that the component is not re-rendered. Even with the `newArray`, what is displayed is not changed, so it won't render.

Please feel free to continue questions.

**Comment by ShamansCoding** [comment] 2020-10-09 09:29
It a bit problem, because in many places in my app I use storage values as useEffect() dependency. All logic is built around changes of the dependency objects then they actually changed. Not only object refs. 

So I cannot use react-tracked as in-place replacement of the original store. It changes the logic behavior in my case.

The array is really changed, values in it changed, but my code will never react to it in useEffect(). Which by the logic should.

It is very unexpected to change inner the array values with no impact on the subscribed useEffect().

**Comment by dai-shi** [comment] 2020-10-09 09:54
> So I cannot use react-tracked as in-place replacement of the original store.

It's very unfortunate.

I guess because useEffect deps are not evaluated in the render phase.
If I add `console.log(myArrayInStore)` in MyComponent, useEffect fires.

Anyway, I'd admit there's a pitfall when using object reference identity and the deep access at the same time. We had this sort of issue with `React.memo` too, and had to provide custom `memo`.

I wasn't aware this could happen with useEffect deps. You revealed a limitation.. We have a workaround `trackMemo`, but it's not exposed now in favor of custom `memo`. Soooo, if we provide a custom `useEffect` we could technically solve this issue. Not super nice.

**Comment by ShamansCoding** [comment] 2020-10-09 10:22
Thanks for your reply! I'm watching for this project for a long time and I hope in the future there will be a way to fix this. I think that approach of react-tracked is right thing to manage the state in the modern React app.

**Comment by dai-shi** [comment] 2020-10-09 12:22
Note: The current recommendation for this use case is to use `useSelector` instead. It's not in-place replacement.

**Comment by dai-shi** [comment] 2020-12-02 16:06
Closing this as answered.

**Closed by dai-shi** 2020-12-02 16:06 UTC
